/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "types_xdr.h"

bool_t xdr_map_t (XDR *xdrs, map_t *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, (2 +  HEIGHT*LENGTH )* BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_vector (xdrs, (char *)objp->tab, HEIGHT*LENGTH,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->start_pos))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->max_score))
				 return FALSE;
		} else {
			{
				register int *genp;

				for (i = 0, genp = objp->tab;
					i < HEIGHT*LENGTH; ++i) {
					IXDR_PUT_LONG(buf, *genp++);
				}
			}
			IXDR_PUT_LONG(buf, objp->start_pos);
			IXDR_PUT_LONG(buf, objp->max_score);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, (2 +  HEIGHT*LENGTH )* BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_vector (xdrs, (char *)objp->tab, HEIGHT*LENGTH,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->start_pos))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->max_score))
				 return FALSE;
		} else {
			{
				register int *genp;

				for (i = 0, genp = objp->tab;
					i < HEIGHT*LENGTH; ++i) {
					*genp++ = IXDR_GET_LONG(buf);
				}
			}
			objp->start_pos = IXDR_GET_LONG(buf);
			objp->max_score = IXDR_GET_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_vector (xdrs, (char *)objp->tab, HEIGHT*LENGTH,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->start_pos))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->max_score))
		 return FALSE;
	return TRUE;
}

bool_t xdr_server_info_t (XDR *xdrs, server_info_t *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, (1 + ( SERVER_LIST_MAX )) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_vector (xdrs, (char *)objp->id, SERVER_LIST_MAX,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->size))
				 return FALSE;

		} else {
		{
			register int *genp;

			for (i = 0, genp = objp->id;
				i < SERVER_LIST_MAX; ++i) {
				IXDR_PUT_LONG(buf, *genp++);
			}
		}
		IXDR_PUT_LONG(buf, objp->size);
		}
		 if (!xdr_map_t (xdrs, &objp->map))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, (1 + ( SERVER_LIST_MAX )) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_vector (xdrs, (char *)objp->id, SERVER_LIST_MAX,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->size))
				 return FALSE;

		} else {
		{
			register int *genp;

			for (i = 0, genp = objp->id;
				i < SERVER_LIST_MAX; ++i) {
				*genp++ = IXDR_GET_LONG(buf);
			}
		}
		objp->size = IXDR_GET_LONG(buf);
		}
		 if (!xdr_map_t (xdrs, &objp->map))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_vector (xdrs, (char *)objp->id, SERVER_LIST_MAX,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->size))
		 return FALSE;
	 if (!xdr_map_t (xdrs, &objp->map))
		 return FALSE;
	return TRUE;
}
